Exercise 1: Use all four features to train the model and use cross validaton to check if the results better? Briefly explain why

In perceptron model when we use four features we have more accuracy rate compared to two or less




In [306]:
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()
#iris.data

In [307]:
X = iris.data[:]

In [308]:
y = iris.target

In [309]:
print('Class labels:', np.unique(y))

Class labels: [0 1 2]


In [310]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=1, stratify=y)

In [311]:
print('Labels counts in y:', np.bincount(y))
print('Labels counts in y_train:', np.bincount(y_train))
print('Labels counts in y_test:', np.bincount(y_test))

Labels counts in y: [50 50 50]
Labels counts in y_train: [35 35 35]
Labels counts in y_test: [15 15 15]


In [312]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler() #center the distribution around zero (mean), with a standard deviation of 1.
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [313]:
from sklearn.linear_model import Perceptron

ppn = Perceptron(max_iter=100, eta0=0.1, random_state=42)
ppn.fit(X_train_std, y_train)

Perceptron(eta0=0.1, max_iter=100, random_state=42)

In [314]:
y_pred = ppn.predict(X_test_std)
print('Misclassified samples: ' + str((y_test != y_pred).sum()))

Misclassified samples: 3


In [315]:
from sklearn.metrics import accuracy_score

print('Accuracy: ' + str(accuracy_score(y_test, y_pred)))

Accuracy: 0.9333333333333333


In [316]:
X_new = [[5.8,4.0,1.2,0.2],[5.8,2.7,3.9,1.2], [5.8,2.7,5.1,1.9]]
y_new = ppn.predict(X_new)
y_new

array([1, 1, 2])

In [317]:
from sklearn.model_selection import cross_val_score
cross_val_score(ppn, X_train_std, y_train, cv=4, scoring="accuracy")

array([0.92592593, 0.88461538, 0.84615385, 0.88461538])

Exercise 2: Try with the scikit-learn stochastic gradient descent model instead of perceptron. Use all four features. Evaluate with cross-validation how does the model perform in terms of accuracy using both two features and four features



In [330]:
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()
X = iris.data[:]
y = iris.target
print('Class labels:', np.unique(y))

print('Labels counts in y_train:', np.bincount(y_train))
print('Labels counts in y_test:', np.bincount(y_test))
print('Labels counts in y:', np.bincount(y))

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.3, random_state=1, stratify=y)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler() 
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score

sgd = SGDClassifier(random_state=42)
sgd.fit(X_train_std, y_train)
y_pred = sgd.predict(X_test_std)

print('Misclassified samples: ' + str((y_test != y_pred).sum()))
print('Accuracy: ' + str(accuracy_score(y_test,y_pred)))
X_new = [[5.8,4.0,1.2,0.2],[5.8,2.7,3.9,1.2], [5.8,2.7,5.1,1.9]]
y_new = sgd.predict(X_new)
y_new

from sklearn.model_selection import cross_val_score
cross_val_score(sgd, X_train_std, y_train, cv=4, scoring="accuracy")

Class labels: [0 1 2]
Labels counts in y: [50 50 50]
Labels counts in y_train: [35 35 35]
Labels counts in y_test: [15 15 15]
Misclassified samples: 5
Accuracy: 0.8888888888888888


array([1.        , 0.96153846, 0.84615385, 0.88461538])

In [332]:
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()
X = iris.data[:, [1,2]]
y = iris.target

print('Class labels:', np.unique(y))
print('Labels counts in y:', np.bincount(y))
print('Labels counts in y_train:', np.bincount(y_train))
print('Labels counts in y_test:', np.bincount(y_test))

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.3, random_state=1, stratify=y)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler() 
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
sgd = SGDClassifier(random_state=42)

sgd.fit(X_train_std, y_train)
y_pred = sgd.predict(X_test_std)
print('Misclassified samples: ' + str((y_test != y_pred).sum()))
print('Accuracy: ' + str(accuracy_score(y_test,y_pred)))

X_new = [[4.0,1.2],[2.7,3.9], [2.7,5.1]]
y_new = sgd.predict(X_new)
y_new

from sklearn.model_selection import cross_val_score
cross_val_score(sgd, X_train_std, y_train, cv=4, scoring="accuracy")

Class labels: [0 1 2]
Labels counts in y: [50 50 50]
Labels counts in y_train: [35 35 35]
Labels counts in y_test: [15 15 15]
Misclassified samples: 3
Accuracy: 0.9333333333333333


array([0.92592593, 0.96153846, 0.88461538, 0.88461538])

it claerly evident with above cases that two features have more accuracy compared to four features